# Provides 2 endpoints: 
#   - Elastic Search HTTP (http://localhost:9200/)
#   - Kibana HTTP (http://localhost:8080/)
version: '3'
services:
    elasticsearch:
        image: elasticsearch
        hostname: elasticsearch
        ports: [ "9200:9200" ]
        networks:
            - elkstack
        volumes:
            # Note that the directories on the left half
            #  need to exist. Otherwise, docker-compose
            #  will fail since it will attempt to mount
            #  non-existing directories.
            - ./elasticsearch/data:/elasticsearch/data
            - ./elasticsearch/logs:/elasticsearch/logs
    logstash:
        image: logstash
        hostname: logstash
        depends_on: [ "elasticsearch" ]
        # Remember to publish the ports you want as inputs
        #  to logstash
        # ports: [ "5044:5044" ]
        networks:
            - elkstack
        volumes:
            # Note that the directories on the left half
            #  need to exist. Otherwise, docker-compose
            #  will fail since it will attempt to mount
            #  non-existing directories.
            - ./logstash/data:/logstash/data
            - ./logstash/logs:/logstash/logs
    kibana:
        image: kibana
        hostname: kibana
        ports: [ "8080:5601" ]
        depends_on: [ "elasticsearch" ]
        networks:
            - elkstack
networks:
    elkstack:
        driver: bridge
        ipam:
            config:
            - subnet: 172.25.0.0/24